language: perl
perl:
  - "5.20"
  - "5.18"
install:
# Deal with dependencies
- cpanm --notest --installdeps ./Twitter-EuropeanaBot
script:
- cd Twitter-EuropeanaBot
- perl Makefile.PL
- make
- make test
